# Generated by Django 3.0.8 on 2020-08-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_id',
            field=models.IntegerField(default=0),
        ),
    ]
